# -*- coding: utf-8 -*-
{
    'name': "LYM Portal",
    'summary': """LYM Portal""",
    'description': """LYM Portal""",
    'author': "Lymtech",
    'website': "http://www.lymtech.com.br",
    'category': 'Uncategorized',
    'version': '14.0.1.0.0',
    # 'depends': ['base', 'portal', 'website_form', 'lym_sponsor', 'lym_css', 'lym_expositores'],
    'depends': ['base', 'portal', 'website_form', 'lym_sponsor',  'lym_expositores'],
    'data': [
        'security/ir.model.access.csv',
        'views/myportal.xml'
        # ,
        # 'views/cadastro_curso.xml',
        # 'views/cadastro_video.xml',
        # 'views/cadastro_catalogo.xml',
        # 'views/cadastro_produto.xml',
        # 'views/cadastro_banner.xml',
        # 'views/cadastro_representante.xml',
        # 'views/view_cursos.xml',
        # 'views/view_videos.xml',
        # 'views/view_catalogos.xml',
        # 'views/view_produtos.xml',
        # 'views/view_banners.xml',
        # 'views/view_representantes.xml',
        # 'views/view_salas.xml',
        # 'views/edit_curso.xml',
        # 'views/edit_video.xml',
        # 'views/edit_catalogo.xml',
        # 'views/edit_produto.xml',
        # 'views/edit_informacao.xml',
        # 'views/edit_banner.xml',
        # 'views/edit_representante.xml',
    ],
    'application': True,
    'auto_install': False
}
